// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // Prefer values from FlutterFire after `flutterfire configure --platforms=web`.
      // Until then, pass the Web app id from Firebase Console (Project settings → Your apps → Web):
      //   flutter run -d chrome --dart-define=FIREBASE_WEB_APP_ID=1:...:web:...
      // Optional if the Web API key differs from Android:
      //   --dart-define=FIREBASE_WEB_API_KEY=...
      const webAppId = String.fromEnvironment('FIREBASE_WEB_APP_ID');
      const webApiKey = String.fromEnvironment(
        'FIREBASE_WEB_API_KEY',
        defaultValue: 'AIzaSyCgsDq1vUZ4gfIgGurSQti35F8NpVNjCew',
      );
      if (webAppId.isEmpty) {
      return web;
      }
      return FirebaseOptions(
        apiKey: webApiKey,
        appId: webAppId,
        messagingSenderId: '345774178337',
        projectId: 'haver-bahatzer',
        authDomain: 'haver-bahatzer.firebaseapp.com',
        storageBucket: 'haver-bahatzer.firebasestorage.app',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgsDq1vUZ4gfIgGurSQti35F8NpVNjCew',
    appId: '1:345774178337:android:d51eace796e57b2c00a360',
    messagingSenderId: '345774178337',
    projectId: 'haver-bahatzer',
    storageBucket: 'haver-bahatzer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2P4OqsFccp1p3BI2J95EmgVv0E1haETU',
    appId: '1:345774178337:ios:4d73f83ba79d0dd700a360',
    messagingSenderId: '345774178337',
    projectId: 'haver-bahatzer',
    storageBucket: 'haver-bahatzer.firebasestorage.app',
    iosBundleId: 'com.haverba.haverBahatzer',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOhAsU0Aj7hQ36bWXNiSLMOkhFuO5hq8c',
    appId: '1:345774178337:web:269be11cc249a3ba00a360',
    messagingSenderId: '345774178337',
    projectId: 'haver-bahatzer',
    authDomain: 'haver-bahatzer.firebaseapp.com',
    storageBucket: 'haver-bahatzer.firebasestorage.app',
    measurementId: 'G-6K39LG5E9H',
  );

}